In [2]:
import numpy as np

In [2]:
a = [12,25,15,1,5]
b = [12,14,23,24,2]

In [4]:
new = a+b
new

[12, 25, 15, 1, 5, 12, 14, 23, 24, 2]

In [7]:
a_arr = np.array(a)
b_arr = np.array(b)
new_arr = np.array(a_arr+b_arr)
new_arr

array([24, 39, 38, 25,  7])

In [21]:
lst = np.array([[12.5,3,54],[5,64,3],[65,41,2]])

In [24]:
lst

array([[12.5,  3. , 54. ],
       [ 5. , 64. ,  3. ],
       [65. , 41. ,  2. ]])

In [25]:
lst.shape

(3, 3)

In [26]:
lst.dtype

dtype('float64')

In [27]:
type(lst)

numpy.ndarray

In [28]:
print(lst.shape)

(3, 3)


In [29]:
lst2 = (lst,float)

In [30]:
lst2

(array([[12.5,  3. , 54. ],
        [ 5. , 64. ,  3. ],
        [65. , 41. ,  2. ]]), float)

In [34]:
lsta = []
for i in range(11):
    lsta.append(i)
print(lsta)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [35]:
lsta_arr = np.arange(11)

In [36]:
lsta_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
lstb = [lsta_arr**2]

In [38]:
lstb

[array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)]

# list comprehension

In [39]:
lstc = [i**3 for i in range(11)]
lstc

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

# performance measurement

In [4]:
lstn = range(10000)
%timeit [i**2 for i in lstn ]

7.65 ms ± 6.75 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
lstn_arr = np.arange(10000)
%timeit lstn_arr**2


18.7 µs ± 97.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# creating numpy array

In [6]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(1000,200,-200)

array([1000,  800,  600,  400])

In [12]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.zeros([4,3],dtype=np.int32)
# float value wont be displayed

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
x=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(x)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [16]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
np.ones([3,2],dtype=np.int32)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.full([4,3],2.2)

array([[2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2]])

In [25]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
v = np.array([1,2,3,4])
u = np.array([5,6,7,8])
v,u

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [31]:
np.tile([1,2,3],[3,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

# To create random values

In [32]:
np.random.random(11)

array([0.5588199 , 0.19465667, 0.15130189, 0.20657877, 0.63045854,
       0.11941997, 0.43613462, 0.72829079, 0.20679497, 0.64376412,
       0.08134933])

In [7]:
np.random.seed(12)
print(np.random.random())

0.15416284237967237


In [9]:
np.random.seed(12)
print(np.random.random())

0.15416284237967237


In [10]:
np.random.random(11)

array([0.7400497 , 0.26331502, 0.53373939, 0.01457496, 0.91874701,
       0.90071485, 0.03342143, 0.95694934, 0.13720932, 0.28382835,
       0.60608318])

In [13]:
x = np.random.random([4,4])
x

array([[0.41925027, 0.42405245, 0.46314887, 0.37372315],
       [0.4655081 , 0.03516826, 0.08427267, 0.7325207 ],
       [0.63619999, 0.02790779, 0.30017006, 0.22085252],
       [0.05501999, 0.52324607, 0.41636966, 0.04821875]])

In [14]:
x1 = np.round(x,2)

In [15]:
x1

array([[0.42, 0.42, 0.46, 0.37],
       [0.47, 0.04, 0.08, 0.73],
       [0.64, 0.03, 0.3 , 0.22],
       [0.06, 0.52, 0.42, 0.05]])

In [19]:
new = x1*100
new

array([[42., 42., 46., 37.],
       [47.,  4.,  8., 73.],
       [64.,  3., 30., 22.],
       [ 6., 52., 42.,  5.]])

In [21]:
m = np.random.random([3,2])
m

array([[0.50655608, 0.46144026],
       [0.89474307, 0.60577769],
       [0.6033556 , 0.44387186]])

In [22]:
m1 = np.round(m,3)
m1

array([[0.507, 0.461],
       [0.895, 0.606],
       [0.603, 0.444]])

In [24]:
m2 = m1*100
m2

array([[50.7, 46.1],
       [89.5, 60.6],
       [60.3, 44.4]])

In [27]:
type(m2)

numpy.ndarray

In [29]:
lst5 = m2.astype(np.int32)
lst5

array([[50, 46],
       [89, 60],
       [60, 44]])

In [30]:
a = np.arange(10)
print(a.dtype)
a

int32


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
v=np.random.random([4,3])
v

array([[0.35544292, 0.33472408, 0.17750637],
       [0.00800334, 0.0104384 , 0.5974588 ],
       [0.08463852, 0.31566824, 0.96861833],
       [0.87358255, 0.91278399, 0.16989826]])

In [44]:
v3 = v*100
v3

array([[35.54429248, 33.47240775, 17.75063672],
       [ 0.80033398,  1.04384021, 59.74588046],
       [ 8.46385204, 31.56682369, 96.8618329 ],
       [87.35825512, 91.27839942, 16.98982609]])

In [47]:
v5 = np.round(v3,2)
v5

array([[35.54, 33.47, 17.75],
       [ 0.8 ,  1.04, 59.75],
       [ 8.46, 31.57, 96.86],
       [87.36, 91.28, 16.99]])

In [45]:
v1 = v3.astype(np.int32)
v1

array([[35, 33, 17],
       [ 0,  1, 59],
       [ 8, 31, 96],
       [87, 91, 16]])